### PR TITLE
Dependencies between configurations (working version)

### PR DESCRIPTION
**Pull request by kamsar**
This is a partially merged version of #78. It has seen significant refactoring and simplification to fit in with the pipeline based control panel and enable extension.

There are still several outstanding work items that need to be addressed:
* The dependencies are not being treated as a tree and need to do so (e.g. you cannot have transitive dependency, and configurations with equal number of dependencies are what is being evaluated as opposed to what depends on what else which can result in incorrect dependency ordering)
* If you request Unicorn sync all configurations (e.g. no configurations query string param) dependency-based ordering is not respected. The code in RenderControlPanel() needs to be refactored out and fixed per above to somewhere - maybe in `ConfigurationDependencyResolver`
* Tests are not written for the dependency resolver and sundry new code. Should include dependency loops and transitive configs for sure.
* It seems like there should be some sort of mechanism to either _enforce_ dependencies (e.g. if you choose A which depends on B that automatically syncs B then A even without B selected), or otherwise add 'teeth' to them. Maybe I'm wrong here. Would love feedback.

### CODE REVIEW

**Comment by kamsar** [comment]
To be clear @Eldblom I'm not saying you have to do anything necessarily, just that here's my WIP if you want to help or have commentary :)

**Comment by kamsar** [comment]
This has been cleaned up and merged.

* Dependencies can resolve as a tree, including transitively with loop detection
* Tests are written on the dependency resolution logic
* _Implicit dependency was REMOVED because it was extremely dependency laden and nigh impossible to test_. I'm not opposed to the idea of implicit dependency but it needs a less code-smelly implementation, and it needs to come with tests.

**Comment by kamsar** [comment]
Unicorn 3.1.0-beta04 is now on NuGet, which includes dependency support for your perusal @Eldblom .

NOTE: there are some YAML format changes in Rainbow 1.1/Unicorn 3.1. Existing YAML files can be read by the new version however items saved by the new version cannot be read by older versions. To normalize, I would suggest syncing before upgrade and reserializing after upgrade.

**Comment by Eldblom** [comment]
Thanks @kamsar. Will be tested asap.
Totally understand all your points - the implicit dependencies was more of a test of the theory really so I understand that it's gone. Cool that you got the dependency sync in there - which for me was more blocked by the current UI implementation than anything else.

**Pull request merged**
