### PR TITLE
Feature: allow exceptions without descendants

### PR DESCRIPTION
**Pull request by mortenbock**
See issue #251.

Allows to make an exception for only a parent node.

### CODE REVIEW

**Comment by kamsar** [comment]
Looks good visually, will need to actually run it before merging :)

**Comment by mortenbock** [comment]
Don't merge it just yet. I think I found a bug :)

**Comment by mortenbock** [comment]
Ok, so this is very strange. What I'm trying to accomplish is to not import the children of the "Widgets" folders, even though they are on disc.

It looks like my code changes work, because the unit tests pass, and the log shows this when running a Sync operation:

    [S] master:/sitecore/content/MyCompany/MySite/DK/SiteData/Widgets/Mbs Content Tile (6842da58-4365-4661-b7d1-8d403b4e2449) by Serialization Preset Predicate but it was in Serialization File System Data Store. Children of /sitecore/content/MyCompany/MySite/DK/ excluded
    This usually indicates an extraneous excluded serialized item is present in the Children of /sitecore/content/MyCompany/MySite/DK/ excluded, which should be removed.
    [S] master:/sitecore/content/MyCompany/MySite/DK/SiteData/Widgets/Test tile (4de56d8c-bfe1-4f6d-9ff3-8e1d54d864e4) by Serialization Preset Predicate but it was in Serialization File System Data Store. Children of /sitecore/content/MyCompany/MySite/DK/ excluded
    This usually indicates an extraneous excluded serialized item is present in the Children of /sitecore/content/MyCompany/MySite/DK/ excluded, which should be removed.
    [S] master:/sitecore/content/MyCompany/MySite/DK/SiteData/Widgets/Foo tile (4464f9da-cd7f-4120-9798-c2dcf76b91d2) by Serialization Preset Predicate but it was in Serialization File System Data Store. Children of /sitecore/content/MyCompany/MySite/DK/ excluded
    This usually indicates an extraneous excluded serialized item is present in the Children of /sitecore/content/MyCompany/MySite/DK/ excluded, which should be removed.
    [S] master:/sitecore/content/MyCompany/MySite/SE/SiteData/Widgets/Swedish tile (3bd12138-3212-432e-9c71-fd3448e42498) by Serialization Preset Predicate but it was in Serialization File System Data Store. Children of /sitecore/content/MyCompany/MySite/SE/ excluded
    This usually indicates an extraneous excluded serialized item is present in the Children of /sitecore/content/MyCompany/MySite/SE/ excluded, which should be removed.

So here's where it gets weird. After the sync has completed, the database now contains:
- Mbs Content Tile
- Test tile
- Swedish tile

But it does NOT contain the "Foo tile".

I searched for the id's in the unicorn folders, and they all seem to be referenced on other excluded items? What could be the reason that some of them get included in the sync?

If I delete the Widgets folders from the DB and run the sync again, only the folder is created, and none of the widgets. 

My include looks like this, and uses the `NewItemOnlyEvaluator`

    <include name="Content" database="master" path="/sitecore/content/MyCompany/MySite">
      <exclude childrenOfPath="DK">
        <except name="SiteData" includeChildren="false"/>
        <except name="SiteData/SiteConfiguration" includeChildren="false"/>
        <except name="SiteData/Widgets" includeChildren="false"/>
        <except name="Checkout"/>
        <except name="Search"/>
        <except name="Offers"/>
        <except name="NotFound"/>
      </exclude>
      <exclude childrenOfPath="SE">
        <except name="SiteData" includeChildren="false"/>
        <except name="SiteData/SiteConfiguration" includeChildren="false"/>
        <except name="SiteData/Widgets" includeChildren="false"/>
        <except name="Checkout"/>
        <except name="Search"/>
        <except name="Offers"/>
        <except name="NotFound"/>
      </exclude>
    </include>

**Comment by mortenbock** [comment]
Ok, after digging more into this, it seems that the issue may have been a red herring of some sort. If I run the sync on a completely fresh DB install, it works as expected.

**Comment by mortenbock** [comment]
@kamsar Just checking in if you know when you will be able to take a look at this PR? :)

We are currently deploying with a custom build, so my little yellow note is reminding me to check for updates here.

**Comment by richardszalay** [comment]
Does this feature work with Dilithium?

**Pull request merged**
